# Generated by Django 5.1.1 on 2024-09-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerorder',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default=None, max_length=5, verbose_name='Order_ID')),
                ('table_number', models.CharField(max_length=5, verbose_name='Table_Number')),
                ('food', models.CharField(max_length=5, verbose_name='Food_ID')),
                ('order_date', models.DateField(verbose_name='Order_Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Foodcategory',
            fields=[
                ('catename', models.CharField(default=None, max_length=50, primary_key=True, serialize=False, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Foodmenu',
            fields=[
                ('foodid', models.AutoField(primary_key=True, serialize=False, verbose_name='Food_ID')),
                ('foodname', models.CharField(default=None, max_length=50, verbose_name='Food Name')),
                ('description', models.CharField(default=None, max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Price')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='img')),
                ('deleted', models.BooleanField(default=False)),
                ('soldout', models.BooleanField(default=False)),
                ('catename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.foodcategory', verbose_name='Category Name')),
            ],
            options={
                'ordering': ['foodid'],
            },
        ),
    ]
