# Generated by Django 5.1.1 on 2024-09-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodmenu',
            fields=[
                ('food_id', models.CharField(db_column='Food_ID', max_length=4, primary_key=True, serialize=False)),
                ('food_name', models.CharField(db_column='Food_Name', max_length=50)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
            ],
        ),
    ]
