# Generated by Django 5.1.1 on 2024-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='img',
            field=models.ImageField(db_column='Img', default=111, upload_to='images/', verbose_name='food image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='food_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Food_ID'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='food_name',
            field=models.CharField(max_length=50, verbose_name='Food_Name'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
