# Generated by Django 5.1.1 on 2024-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
