# Generated by Django 5.1.1 on 2024-09-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_foodmenu_img_alter_foodmenu_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['food_id']},
        ),
    ]
