# Generated by Django 5.1.1 on 2024-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_foodmenu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='food_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='FoodID'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='food_name',
            field=models.CharField(max_length=50, verbose_name='FoodName'),
        ),
    ]
