# Generated by Django 5.1.1 on 2024-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_customerorder_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cancled',
            field=models.BooleanField(default=False),
        ),
    ]
