# Generated by Django 5.1.1 on 2024-09-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_customerorder_cancled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Receipt_ID')),
                ('invoice', models.CharField(max_length=5, verbose_name='Invoice_ID')),
                ('order', models.CharField(default=None, max_length=5, verbose_name='Order_ID')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Payment_Method')),
                ('payment_amout', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment_Amout')),
                ('recept_date', models.DateField(verbose_name='Recept_Date')),
            ],
        ),
    ]
