# Generated by Django 5.1.1 on 2024-09-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_foodmenu_food_id_alter_foodmenu_food_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'ordering': ['foodid']},
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='food_name',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='foodid',
            field=models.CharField(default=111, max_length=4, primary_key=True, serialize=False, verbose_name='Food_ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='foodname',
            field=models.CharField(default=111, max_length=50, verbose_name='Food_Name'),
            preserve_default=False,
        ),
    ]
