# Generated by Django 5.1.1 on 2024-09-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_foodmenu_options_remove_foodmenu_food_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerorder',
            fields=[
                ('order_id', models.CharField(db_column='Order_ID', max_length=5, primary_key=True, serialize=False)),
                ('table_number', models.CharField(db_column='Table_Number', max_length=5)),
                ('order_date', models.DateField(db_column='Order_Date')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('food', models.ForeignKey(db_column='Food_ID', on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.foodmenu')),
            ],
        ),
    ]
