# Generated by Django 5.1.1 on 2024-09-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['invoice']},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.CharField(max_length=6, verbose_name='Invoice_ID'),
        ),
    ]
