# Generated by Django 5.1.1 on 2024-09-23 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_alter_receipt_options_alter_receipt_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='recept_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Recept Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.CharField(max_length=6, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.CharField(default=None, max_length=5, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_amout',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amout'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Receipt ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='recept_date',
            field=models.DateField(verbose_name='Recept Date'),
        ),
    ]
