# Generated by Django 5.1.1 on 2024-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_customerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='img',
            field=models.ImageField(db_column='Img', default=None, upload_to='images/', verbose_name='food image'),
        ),
    ]
