# Generated by Django 5.1.1 on 2024-09-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_foodmenu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='description',
            field=models.CharField(default=None, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='foodid',
            field=models.CharField(default='0000', max_length=4, primary_key=True, serialize=False, verbose_name='Food_ID'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='foodname',
            field=models.CharField(default=None, max_length=50, verbose_name='Food_Name'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Price'),
        ),
    ]
