# Generated by Django 5.1.2 on 2024-10-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_receipt_recept_time_alter_receipt_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='foodname',
            field=models.CharField(default=None, max_length=50, verbose_name='Food_Name'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Price'),
        ),
    ]
