# Generated by Django 5.1.1 on 2024-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_alter_foodmenu_foodid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='foodid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Food_ID'),
        ),
    ]
