# Generated by Django 5.1.1 on 2024-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_alter_foodmenu_foodid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='img',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='food image'),
        ),
    ]
