# Generated by Django 5.1.1 on 2024-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_alter_foodmenu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='img'),
        ),
    ]
