# Generated by Django 5.1.1 on 2024-09-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_foodmenu_deleted_alter_foodmenu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodcategory',
            fields=[
                ('catename', models.AutoField(primary_key=True, serialize=False, verbose_name='Category_Name')),
            ],
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='catename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.foodcategory', verbose_name='Category_Name'),
        ),
    ]
