# Generated by Django 5.1.1 on 2024-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_foodcategory_foodmenu_catename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='catename',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False, verbose_name='Category_Name'),
        ),
    ]
