# Generated by Django 5.1.1 on 2024-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0014_alter_foodcategory_catename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='catename',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='foodname',
            field=models.CharField(default=None, max_length=50, verbose_name='Food Name'),
        ),
    ]
