# Generated by Django 5.1.1 on 2024-09-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0015_alter_foodcategory_catename_alter_foodmenu_foodname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='catename',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='catename',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='restaurant_app.foodcategory', verbose_name='Category_Name'),
        ),
    ]
