# Generated by Django 5.1.1 on 2024-09-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0016_alter_foodcategory_catename_alter_foodmenu_catename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='catename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.foodcategory', verbose_name='Category_Name'),
        ),
    ]
